[package]
name = "bridge"
version = "0.1.0"
edition = "2018"
description = "This will stand on lua's side and interact with `core`"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.14"
log4rs = "1.0.0"
mlua = { version = "0.6.2", features = ["module", "async", "send"] }
serde = "1.0.130"
serde_json = "1.0.67"
tokio = { version = "1.11.0", features = ["rt-multi-thread", "time", "sync"] }
linearf = { path = "../core" }
registrar = { path = "../registrar/registrar" }
