[package]
name = "registrar-preprocessor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.9"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
toml = "0.5.8"
